// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxm9NlHVALVsA1xV71Q8wdgX3msQxE5TE',
    appId: '1:868921740099:web:1c7e0c70f2119c04e5bdf6',
    messagingSenderId: '868921740099',
    projectId: 'varlik-yonetimi-a9cff',
    authDomain: 'varlik-yonetimi-a9cff.firebaseapp.com',
    storageBucket: 'varlik-yonetimi-a9cff.appspot.com',
    measurementId: 'G-QDF2HP3V7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxyLgmJ3ZKv-JQzaLsDzrflUXlM7wxwMo',
    appId: '1:868921740099:android:08f93620fadcee08e5bdf6',
    messagingSenderId: '868921740099',
    projectId: 'varlik-yonetimi-a9cff',
    storageBucket: 'varlik-yonetimi-a9cff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiz_cudMrrFcXdF5U_9mxWshaQDUMINSA',
    appId: '1:868921740099:ios:5c94099c3e587fe5e5bdf6',
    messagingSenderId: '868921740099',
    projectId: 'varlik-yonetimi-a9cff',
    storageBucket: 'varlik-yonetimi-a9cff.appspot.com',
    iosBundleId: 'com.example.varlikYonetimi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiz_cudMrrFcXdF5U_9mxWshaQDUMINSA',
    appId: '1:868921740099:ios:1c1925c1752e1760e5bdf6',
    messagingSenderId: '868921740099',
    projectId: 'varlik-yonetimi-a9cff',
    storageBucket: 'varlik-yonetimi-a9cff.appspot.com',
    iosBundleId: 'com.example.varlikYonetimi.RunnerTests',
  );
}
